/* eslint-disable react-refresh/only-export-components -- This context module intentionally exports its provider and hook together. */

import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from 'react'

export type Theme = 'dark' | 'light'
export type Locale = 'zh' | 'en'

export const PREFERENCE_STORAGE_KEYS = {
  theme: 'cosmos.theme',
  locale: 'cosmos.locale',
} as const

const zh = {
  'preferences.controls': '显示与语言偏好',
  'preferences.switchToLight': '切换到浅色模式',
  'preferences.switchToDark': '切换到深色模式',
  'preferences.switchToEnglish': '切换到英文',
  'preferences.switchToChinese': '切换到中文',

  'nav.mainLabel': '主导航',
  'nav.workspace': '工作区',
  'nav.controlPlane': '控制中心',
  'nav.runs': '自动化运行',
  'nav.sessions': '会话',
  'nav.automations': '自动化',
  'nav.experts': '专家库',
  'nav.repositories': '代码仓库',
  'nav.integrations': '集成',
  'nav.governance': '治理中心',
  'nav.activity': '事件日志',
  'nav.recentRuns': '最近运行',
  'nav.recentSessions': '最近会话',

  'common.newTask': '新建任务',
  'common.search': '搜索',
  'common.close': '关闭',
  'common.cancel': '取消',
  'common.create': '创建',
  'common.save': '保存',
  'common.delete': '删除',
  'common.edit': '编辑',
  'common.rename': '重命名',
  'common.archive': '归档',
  'common.restore': '恢复',
  'common.retry': '重试',
  'common.approve': '批准',
  'common.requestChanges': '要求修改',
  'common.send': '发送',
  'common.open': '打开',
  'common.more': '更多操作',
  'common.back': '返回',
  'common.refresh': '刷新',
  'common.filter': '筛选',
  'common.clear': '清除',
  'common.viewAll': '查看全部',
  'common.pause': '暂停',
  'common.resume': '继续',
  'common.stop': '停止',
  'common.confirm': '确认',
  'common.loading': '加载中',
  'common.loadMore': '加载更多',
  'common.loadingMore': '正在加载',
  'common.noData': '暂无数据',

  'status.draft': '草稿',
  'status.queued': '排队中',
  'status.running': '运行中',
  'status.waiting': '待审批',
  'status.completed': '已完成',
  'status.failed': '失败',
  'status.paused': '已暂停',
  'status.canceled': '已取消',

  'workbench.viewLabel': '会话视图',
  'workbench.agent': 'Agent',
  'workbench.conversation': '对话',
  'workbench.changes': '变更',
  'workbench.terminal': '终端',
  'workbench.files': '文件',
  'workbench.approval': '审批',
  'workbench.subscriptions': '订阅',
  'workbench.details': '会话详情',
  'workbench.stages': '运行阶段',
  'workbench.openNavigation': '打开导航',
  'workbench.pauseRun': '暂停运行',
  'workbench.resumeRun': '继续运行',
  'workbench.stopRun': '停止运行',
  'workbench.shareSession': '分享会话',
  'workbench.closeInspector': '关闭详情面板',
  'workbench.openInspector': '打开详情面板',
  'workbench.retryStep': '重试步骤',
  'workbench.inputPlaceholder': '询问任何问题，或输入 / 使用命令…',
  'workbench.sendInstruction': '发送指令',
  'workbench.taskBrief': '任务摘要',
  'workbench.working': '执行中',
  'workbench.noApprovalTitle': '当前没有待处理审批',
  'workbench.noApprovalDescription': '低风险步骤会按工作区策略自动放行。',
  'workbench.mediumRisk': '中风险',
  'workbench.policyDecision': '策略决策',
  'workbench.testsPassed': '126 项测试通过',
  'workbench.changedFilesSummary': '5 个变更文件',
  'workbench.rollbackReady': '已生成回滚方案',
  'workbench.approveContinue': '批准并继续',
  'workbench.decisionRecorded': '决策已记录，正在创建 PR',
  'workbench.attachFile': '添加附件',
  'workbench.selectModel': '选择模型',
  'workbench.readOnlyReplay': '只读回放',
  'workbench.terminalOutput': '终端输出',
  'workbench.changedFiles': '变更文件',
  'workbench.codeDiff': '代码差异',
  'workbench.splitView': '并排视图',
  'workbench.queuedInstruction': '追加指令',
  'workbench.justNow': '刚刚',
  'workbench.executeAfterStep': '将在当前步骤结束后执行',
  'workbench.addedToContext': '已加入运行上下文',

  'stage.trigger': '触发',
  'stage.plan': '规划',
  'stage.author': '编码',
  'stage.verify': '验证',
  'stage.approval': '审批',
  'stage.deliver': '交付',

  'inspector.eyebrow': '会话检查器',
  'inspector.currentExecutor': '当前执行者',
  'inspector.policyConstrained': '受策略约束',
  'inspector.online': '在线',
  'inspector.metrics': '执行指标',
  'inspector.elapsed': '耗时',
  'inspector.stages': '阶段',
  'inspector.context': '上下文',
  'inspector.estimatedCost': '预计成本',
  'inspector.contextSources': '上下文来源',
  'inspector.codeGraph': '代码图谱',
  'inspector.relatedFiles': '14 个相关文件',
  'inspector.teamStandards': '团队规范',
  'inspector.changeHistory': '历史变更',
  'inspector.similarPrs': '3 个相似 PR',
  'inspector.permissions': '权限边界',
  'inspector.codeWrite': '代码写入',
  'inspector.temporaryBranch': '临时分支',
  'inspector.externalNetwork': '外部网络',
  'inspector.allowlist': '允许列表',
  'inspector.mergePermission': '合并权限',
  'inspector.approvalRequired': '需审批',

  'runs.title': '运行记录',
  'runs.description': '观察、接管和回放所有 Agent 交付任务',
  'runs.overview': '运行概览',
  'runs.waiting': '待审批',
  'runs.waitingHint': '需要负责人决策',
  'runs.runningHint': '2 个沙箱活跃',
  'runs.failedHint': '可从断点恢复',
  'runs.completedToday': '今日完成',
  'runs.completedHint': '一次通过率 92.4%',
  'runs.eyebrow': '全部运行',
  'runs.recent': '最近执行',
  'runs.searchPlaceholder': '搜索任务或仓库',

  'automations.title': '自动化',
  'automations.description': '将触发器、专家、审批策略和交付动作编排成可复用流程',
  'automations.create': '创建自动化',
  'automations.eyebrow': '已发布工作流',
  'automations.listTitle': '交付流程',
  'automations.settings': '自动化设置',
  'automations.trigger': '触发器',
  'automations.successRate': '成功率',
  'automations.runCount': '运行次数',
  'automations.published': '已发布',
  'automations.draft': '草稿',

  'experts.title': '专家模板',
  'experts.description': '个可部署工作流，覆盖软件交付、运维、质量、安全与支持',
  'experts.customTask': '自定义任务',
  'experts.eyebrow': '工作流模板库',
  'experts.count': '个模板',
  'experts.searchPlaceholder': '搜索模板名称或能力',
  'experts.categories': '模板分类',
  'experts.all': '全部',
  'experts.domain': '领域',
  'experts.typicalTrigger': '典型触发',
  'experts.deployable': '可部署',
  'experts.useTemplate': '使用模板',
  'experts.empty': '没有匹配的专家模板',

  'repositories.title': '代码仓库',
  'repositories.description': '管理上下文索引、分支策略和 Agent 可访问范围',
  'repositories.connect': '连接仓库',
  'repositories.eyebrow': '上下文索引',
  'repositories.listTitle': '已索引仓库',
  'repositories.coverage': '索引覆盖',
  'repositories.lastSync': '最后同步',
  'repositories.strictPolicy': '严格策略',
  'repositories.standardPolicy': '标准策略',
  'repositories.now': '刚刚',
  'repositories.minutesAgo8': '8 分钟前',
  'repositories.minutesAgo21': '21 分钟前',
  'repositories.hourAgo': '1 小时前',

  'integrations.title': '集成',
  'integrations.description': '连接代码、协作、工单和告警系统',
  'integrations.add': '添加集成',
  'integrations.eyebrow': '已连接服务',
  'integrations.listTitle': '生产连接',
  'integrations.connected': '已连接',
  'integrations.actionRequired': '需要处理',
  'integrations.healthy': '健康',
  'integrations.missingWebhook': '缺少 Webhook',
  'integrations.githubDetail': '32 个仓库 · App 安装',
  'integrations.feishuDetail': '4 个机器人 · 9 个群组',
  'integrations.jiraDetail': '2 个项目 · OAuth',
  'integrations.pagerDutyDetail': '等待配置事件订阅',

  'governance.title': '治理中心',
  'governance.description': '集中处理高风险决策、审批策略与审计证据',
  'governance.policySettings': '策略设置',
  'governance.policyCoverage': '策略覆盖',
  'governance.policyCoverageHint': '4 个仓库待补齐',
  'governance.humanWait': '人工等待中位数',
  'governance.humanWaitHint': '较上周下降 14%',
  'governance.autoDecisions': '本月自动决策',
  'governance.autoDecisionsHint': '无越权事件',
  'governance.eyebrow': '决策收件箱',
  'governance.pending': '待处理决策',
  'governance.matchedPolicy': '命中策略',
  'governance.externalBudget': '外部调用预算',
  'governance.waitTime': '等待时间',
  'governance.empty': '当前没有待处理决策',

  'activity.title': '事件日志',
  'activity.description': '查看所有 Agent、用户与系统动作的不可变记录',
  'activity.filter': '筛选事件',
  'activity.eyebrow': '审计轨迹',
  'activity.recent': '最近事件',

  'newTask.eyebrow': '新运行',
  'newTask.title': '创建交付任务',
  'newTask.titleLabel': '任务标题',
  'newTask.titlePlaceholder': '例如：修复支付回调间歇性超时',
  'newTask.descriptionLabel': '任务说明',
  'newTask.descriptionPlaceholder': '写清目标、约束和验收标准…',
  'newTask.repository': '代码仓库',
  'newTask.expert': '执行专家',
  'newTask.baseBranch': '基础分支',
  'newTask.expertProfile': '专家配置',
  'newTask.tools': '工具',
  'newTask.environment': '环境',
  'newTask.approvalMode': '审批策略',
  'newTask.successRate': '近期成功率',
  'newTask.environment.ephemeral': '临时沙箱',
  'newTask.environment.restricted': '受限网络',
  'newTask.environment.readOnly': '只读分析',
  'newTask.environment.isolated': '隔离环境',
  'newTask.approval.beforeMerge': '合并前审批',
  'newTask.approval.beforeDeploy': '部署前审批',
  'newTask.approval.beforeWrite': '写入前审批',
  'newTask.approval.beforePublish': '发布前审批',
  'newTask.approval.beforeReply': '回复前审批',
  'newTask.approval.releaseGate': '发布门禁',
  'newTask.approval.everyWrite': '每次写入审批',
  'newTask.approval.beforeMigration': '迁移前审批',
  'newTask.approval.beforeChange': '变更前审批',
  'newTask.acceptanceTitle': '验收条件',
  'newTask.acceptanceHint': '选择本次运行必须满足的交付条件',
  'newTask.acceptance.scope': '仅修改任务范围内的代码',
  'newTask.acceptance.tests': '补齐并通过相关测试',
  'newTask.acceptance.review': '输出变更摘要与验证证据',
  'newTask.linkedContext': '已识别上下文',
  'newTask.removeContext': '移除上下文',
  'newTask.preflight': '运行前检查',
  'newTask.repoConnection': '仓库连接',
  'newTask.connected': '已连接',
  'newTask.repoConnectionDetail': '索引已同步，仓库可访问',
  'newTask.permissionPreflight': '权限策略',
  'newTask.ready': '就绪',
  'newTask.permissionDetail': '允许临时分支写入；合并需审批',
  'newTask.startRun': '开始运行',
  'newTask.saveDraft': '保存草稿',
  'newTask.checking': '正在检查…',
  'newTask.checkPassed': '检查通过',
  'newTask.policy': '将自动应用仓库策略与审批规则',
  'newTask.submit': '创建并运行',

  'sessions.title': '会话',
  'sessions.description': '管理、接管和回顾所有 Agent 会话',
  'sessions.new': '新建会话',
  'sessions.searchPlaceholder': '搜索标题、仓库、分支、触发器、步骤或 PR',
  'sessions.active': '活跃',
  'sessions.favorites': '收藏',
  'sessions.archived': '已归档',
  'sessions.library': '会话库',
  'sessions.entity': '会话',
  'sessions.status': '状态',
  'sessions.allStatuses': '全部状态',
  'sessions.status.draft': '草稿',
  'sessions.status.queued': '排队中',
  'sessions.status.running': '运行中',
  'sessions.status.waiting': '待审批',
  'sessions.status.completed': '已完成',
  'sessions.status.failed': '失败',
  'sessions.count': '个会话',
  'sessions.task': '任务',
  'sessions.expert': '专家',
  'sessions.progress': '进度',
  'sessions.updated': '更新时间',
  'sessions.source': '来源',
  'sessions.sourceArtifacts': '来源 / 产物',
  'sessions.signalsAndUpdated': 'PR / 审批 · 更新',
  'sessions.allExperts': '全部专家',
  'sessions.allRepositories': '全部仓库',
  'sessions.allSources': '全部来源',
  'sessions.allTimes': '全部时间',
  'sessions.lastHour': '最近 1 小时',
  'sessions.lastDay': '最近 24 小时',
  'sessions.lastWeek': '最近 7 天',
  'sessions.selectAll': '选择当前全部会话',
  'sessions.selectSession': '选择会话',
  'sessions.selected': '个会话已选择',
  'sessions.bulkArchive': '批量归档',
  'sessions.approvalNeeded': '待审批',
  'sessions.clearSelection': '清除选择',
  'sessions.filters': '会话筛选',
  'sessions.activeFilters': '项筛选已启用',
  'sessions.open': '打开会话',
  'sessions.favorite': '收藏会话',
  'sessions.unfavorite': '取消收藏',
  'sessions.more': '会话操作',
  'sessions.rename': '重命名',
  'sessions.archive': '归档',
  'sessions.restore': '恢复',
  'sessions.delete': '删除',
  'sessions.emptyActive': '暂无活跃会话',
  'sessions.emptyFavorites': '暂无收藏会话',
  'sessions.emptyArchived': '暂无归档会话',
  'sessions.noResults': '没有找到匹配的会话',
  'sessions.clearSearch': '清除搜索',
  'sessions.renameTitle': '重命名会话',
  'sessions.renameDescription': '使用便于团队识别的名称。',
  'sessions.sessionName': '会话名称',
  'sessions.cancel': '取消',
  'sessions.save': '保存',
  'sessions.deleteTitle': '删除会话',
  'sessions.deleteDescription': '此操作将永久删除该会话及其历史记录，且无法撤销。',
  'sessions.deleteConfirm': '确认删除',
  'sessions.menuLabel': '会话操作菜单',
} as const

export type TranslationKey = keyof typeof zh

const en: Record<TranslationKey, string> = {
  'preferences.controls': 'Display and language preferences',
  'preferences.switchToLight': 'Switch to light mode',
  'preferences.switchToDark': 'Switch to dark mode',
  'preferences.switchToEnglish': 'Switch to English',
  'preferences.switchToChinese': 'Switch to Chinese',

  'nav.mainLabel': 'Main navigation',
  'nav.workspace': 'Workspace',
  'nav.controlPlane': 'Control plane',
  'nav.runs': 'Automation runs',
  'nav.sessions': 'Sessions',
  'nav.automations': 'Automations',
  'nav.experts': 'Experts',
  'nav.repositories': 'Repositories',
  'nav.integrations': 'Integrations',
  'nav.governance': 'Governance',
  'nav.activity': 'Activity log',
  'nav.recentRuns': 'Recent runs',
  'nav.recentSessions': 'Recent sessions',

  'common.newTask': 'New task',
  'common.search': 'Search',
  'common.close': 'Close',
  'common.cancel': 'Cancel',
  'common.create': 'Create',
  'common.save': 'Save',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.rename': 'Rename',
  'common.archive': 'Archive',
  'common.restore': 'Restore',
  'common.retry': 'Retry',
  'common.approve': 'Approve',
  'common.requestChanges': 'Request changes',
  'common.send': 'Send',
  'common.open': 'Open',
  'common.more': 'More actions',
  'common.back': 'Back',
  'common.refresh': 'Refresh',
  'common.filter': 'Filter',
  'common.clear': 'Clear',
  'common.viewAll': 'View all',
  'common.pause': 'Pause',
  'common.resume': 'Resume',
  'common.stop': 'Stop',
  'common.confirm': 'Confirm',
  'common.loading': 'Loading',
  'common.loadMore': 'Load more',
  'common.loadingMore': 'Loading more',
  'common.noData': 'No data',

  'status.draft': 'Draft',
  'status.queued': 'Queued',
  'status.running': 'Running',
  'status.waiting': 'Awaiting approval',
  'status.completed': 'Completed',
  'status.failed': 'Failed',
  'status.paused': 'Paused',
  'status.canceled': 'Canceled',

  'workbench.viewLabel': 'Session views',
  'workbench.agent': 'Agent',
  'workbench.conversation': 'Conversation',
  'workbench.changes': 'Changes',
  'workbench.terminal': 'Terminal',
  'workbench.files': 'Files',
  'workbench.approval': 'Approval',
  'workbench.subscriptions': 'Subscriptions',
  'workbench.details': 'Session details',
  'workbench.stages': 'Run stages',
  'workbench.openNavigation': 'Open navigation',
  'workbench.pauseRun': 'Pause run',
  'workbench.resumeRun': 'Resume run',
  'workbench.stopRun': 'Stop run',
  'workbench.shareSession': 'Share session',
  'workbench.closeInspector': 'Close details panel',
  'workbench.openInspector': 'Open details panel',
  'workbench.retryStep': 'Retry step',
  'workbench.inputPlaceholder': 'Ask anything or type / for commands…',
  'workbench.sendInstruction': 'Send instruction',
  'workbench.taskBrief': 'Task brief',
  'workbench.working': 'Working',
  'workbench.noApprovalTitle': 'No pending approvals',
  'workbench.noApprovalDescription': 'Low-risk steps continue automatically under workspace policy.',
  'workbench.mediumRisk': 'Medium risk',
  'workbench.policyDecision': 'Policy decision',
  'workbench.testsPassed': '126 tests passed',
  'workbench.changedFilesSummary': '5 changed files',
  'workbench.rollbackReady': 'Rollback plan ready',
  'workbench.approveContinue': 'Approve and continue',
  'workbench.decisionRecorded': 'Decision recorded. Creating the PR.',
  'workbench.attachFile': 'Attach file',
  'workbench.selectModel': 'Select model',
  'workbench.readOnlyReplay': 'Read-only replay',
  'workbench.terminalOutput': 'Terminal output',
  'workbench.changedFiles': 'Changed files',
  'workbench.codeDiff': 'Code diff',
  'workbench.splitView': 'Split view',
  'workbench.queuedInstruction': 'Additional instruction',
  'workbench.justNow': 'Just now',
  'workbench.executeAfterStep': 'Runs after the current step completes',
  'workbench.addedToContext': 'Added to the run context',

  'stage.trigger': 'Trigger',
  'stage.plan': 'Plan',
  'stage.author': 'Code',
  'stage.verify': 'Verify',
  'stage.approval': 'Approval',
  'stage.deliver': 'Deliver',

  'inspector.eyebrow': 'Session inspector',
  'inspector.currentExecutor': 'Current executor',
  'inspector.policyConstrained': 'Policy constrained',
  'inspector.online': 'Online',
  'inspector.metrics': 'Execution metrics',
  'inspector.elapsed': 'Elapsed',
  'inspector.stages': 'Stages',
  'inspector.context': 'Context',
  'inspector.estimatedCost': 'Est. cost',
  'inspector.contextSources': 'Context sources',
  'inspector.codeGraph': 'Code graph',
  'inspector.relatedFiles': '14 related files',
  'inspector.teamStandards': 'Team standards',
  'inspector.changeHistory': 'Change history',
  'inspector.similarPrs': '3 similar PRs',
  'inspector.permissions': 'Permission boundaries',
  'inspector.codeWrite': 'Code write',
  'inspector.temporaryBranch': 'Temporary branch',
  'inspector.externalNetwork': 'External network',
  'inspector.allowlist': 'Allowlist',
  'inspector.mergePermission': 'Merge permission',
  'inspector.approvalRequired': 'Approval required',

  'runs.title': 'Runs',
  'runs.description': 'Observe, take over, and replay every Agent delivery task',
  'runs.overview': 'Run overview',
  'runs.waiting': 'Awaiting approval',
  'runs.waitingHint': 'Owner decision required',
  'runs.runningHint': '2 active sandboxes',
  'runs.failedHint': 'Resume from the failure point',
  'runs.completedToday': 'Completed today',
  'runs.completedHint': '92.4% first-pass rate',
  'runs.eyebrow': 'All runs',
  'runs.recent': 'Recent runs',
  'runs.searchPlaceholder': 'Search tasks or repositories',

  'automations.title': 'Automations',
  'automations.description': 'Compose triggers, experts, approval policies, and delivery actions into reusable workflows',
  'automations.create': 'Create automation',
  'automations.eyebrow': 'Published workflows',
  'automations.listTitle': 'Delivery workflows',
  'automations.settings': 'Automation settings',
  'automations.trigger': 'Trigger',
  'automations.successRate': 'Success rate',
  'automations.runCount': 'Runs',
  'automations.published': 'Published',
  'automations.draft': 'Draft',

  'experts.title': 'Expert templates',
  'experts.description': 'deployable workflows across delivery, operations, quality, security, and support',
  'experts.customTask': 'Custom task',
  'experts.eyebrow': 'Workflow library',
  'experts.count': 'templates',
  'experts.searchPlaceholder': 'Search template names or capabilities',
  'experts.categories': 'Template categories',
  'experts.all': 'All',
  'experts.domain': 'Domain',
  'experts.typicalTrigger': 'Typical trigger',
  'experts.deployable': 'Deployable',
  'experts.useTemplate': 'Use template',
  'experts.empty': 'No matching expert templates',

  'repositories.title': 'Repositories',
  'repositories.description': 'Manage context indexes, branch policies, and Agent access scopes',
  'repositories.connect': 'Connect repository',
  'repositories.eyebrow': 'Context index',
  'repositories.listTitle': 'Indexed repositories',
  'repositories.coverage': 'Index coverage',
  'repositories.lastSync': 'Last synced',
  'repositories.strictPolicy': 'Strict policy',
  'repositories.standardPolicy': 'Standard policy',
  'repositories.now': 'Just now',
  'repositories.minutesAgo8': '8 minutes ago',
  'repositories.minutesAgo21': '21 minutes ago',
  'repositories.hourAgo': '1 hour ago',

  'integrations.title': 'Integrations',
  'integrations.description': 'Connect code, collaboration, ticketing, and alerting systems',
  'integrations.add': 'Add integration',
  'integrations.eyebrow': 'Connected services',
  'integrations.listTitle': 'Production connections',
  'integrations.connected': 'Connected',
  'integrations.actionRequired': 'Action required',
  'integrations.healthy': 'Healthy',
  'integrations.missingWebhook': 'Webhook missing',
  'integrations.githubDetail': '32 repositories · App installation',
  'integrations.feishuDetail': '4 bots · 9 groups',
  'integrations.jiraDetail': '2 projects · OAuth',
  'integrations.pagerDutyDetail': 'Event subscription awaiting setup',

  'governance.title': 'Governance',
  'governance.description': 'Handle high-risk decisions, approval policies, and audit evidence in one place',
  'governance.policySettings': 'Policy settings',
  'governance.policyCoverage': 'Policy coverage',
  'governance.policyCoverageHint': '4 repositories need coverage',
  'governance.humanWait': 'Median human wait',
  'governance.humanWaitHint': 'Down 14% week over week',
  'governance.autoDecisions': 'Automated decisions this month',
  'governance.autoDecisionsHint': 'No authorization violations',
  'governance.eyebrow': 'Decision inbox',
  'governance.pending': 'Pending decisions',
  'governance.matchedPolicy': 'Matched policy',
  'governance.externalBudget': 'External call budget',
  'governance.waitTime': 'Wait time',
  'governance.empty': 'No pending decisions',

  'activity.title': 'Activity log',
  'activity.description': 'Review the immutable record of Agent, user, and system actions',
  'activity.filter': 'Filter events',
  'activity.eyebrow': 'Audit trail',
  'activity.recent': 'Recent events',

  'newTask.eyebrow': 'New run',
  'newTask.title': 'Create delivery task',
  'newTask.titleLabel': 'Task title',
  'newTask.titlePlaceholder': 'For example: Fix intermittent payment callback timeouts',
  'newTask.descriptionLabel': 'Task description',
  'newTask.descriptionPlaceholder': 'Describe the goal, constraints, and acceptance criteria…',
  'newTask.repository': 'Repository',
  'newTask.expert': 'Execution expert',
  'newTask.baseBranch': 'Base branch',
  'newTask.expertProfile': 'Expert profile',
  'newTask.tools': 'Tools',
  'newTask.environment': 'Environment',
  'newTask.approvalMode': 'Approval policy',
  'newTask.successRate': 'Recent success rate',
  'newTask.environment.ephemeral': 'Ephemeral sandbox',
  'newTask.environment.restricted': 'Restricted network',
  'newTask.environment.readOnly': 'Read-only analysis',
  'newTask.environment.isolated': 'Isolated environment',
  'newTask.approval.beforeMerge': 'Approval before merge',
  'newTask.approval.beforeDeploy': 'Approval before deploy',
  'newTask.approval.beforeWrite': 'Approval before write',
  'newTask.approval.beforePublish': 'Approval before publish',
  'newTask.approval.beforeReply': 'Approval before reply',
  'newTask.approval.releaseGate': 'Release gate',
  'newTask.approval.everyWrite': 'Approve every write',
  'newTask.approval.beforeMigration': 'Approval before migration',
  'newTask.approval.beforeChange': 'Approval before change',
  'newTask.acceptanceTitle': 'Acceptance criteria',
  'newTask.acceptanceHint': 'Choose the delivery conditions this run must satisfy',
  'newTask.acceptance.scope': 'Change only code within the task scope',
  'newTask.acceptance.tests': 'Add and pass relevant tests',
  'newTask.acceptance.review': 'Provide a change summary and verification evidence',
  'newTask.linkedContext': 'Linked context',
  'newTask.removeContext': 'Remove context',
  'newTask.preflight': 'Preflight',
  'newTask.repoConnection': 'Repository connection',
  'newTask.connected': 'Connected',
  'newTask.repoConnectionDetail': 'Index synced and repository accessible',
  'newTask.permissionPreflight': 'Permission policy',
  'newTask.ready': 'Ready',
  'newTask.permissionDetail': 'Temporary branch writes allowed; merge requires approval',
  'newTask.startRun': 'Start run',
  'newTask.saveDraft': 'Save draft',
  'newTask.checking': 'Checking…',
  'newTask.checkPassed': 'Checks passed',
  'newTask.policy': 'Repository policies and approval rules will be applied automatically',
  'newTask.submit': 'Create and run',

  'sessions.title': 'Sessions',
  'sessions.description': 'Manage, take over, and review every Agent session',
  'sessions.new': 'New session',
  'sessions.searchPlaceholder': 'Search titles, repositories, branches, triggers, steps, or PRs',
  'sessions.active': 'Active',
  'sessions.favorites': 'Favorites',
  'sessions.archived': 'Archived',
  'sessions.library': 'Session library',
  'sessions.entity': 'Session',
  'sessions.status': 'Status',
  'sessions.allStatuses': 'All statuses',
  'sessions.status.draft': 'Draft',
  'sessions.status.queued': 'Queued',
  'sessions.status.running': 'Running',
  'sessions.status.waiting': 'Awaiting approval',
  'sessions.status.completed': 'Completed',
  'sessions.status.failed': 'Failed',
  'sessions.count': 'sessions',
  'sessions.task': 'Task',
  'sessions.expert': 'Expert',
  'sessions.progress': 'Progress',
  'sessions.updated': 'Updated',
  'sessions.source': 'Source',
  'sessions.sourceArtifacts': 'Source / Artifacts',
  'sessions.signalsAndUpdated': 'PR / Approval · Updated',
  'sessions.allExperts': 'All experts',
  'sessions.allRepositories': 'All repositories',
  'sessions.allSources': 'All sources',
  'sessions.allTimes': 'Any time',
  'sessions.lastHour': 'Last hour',
  'sessions.lastDay': 'Last 24 hours',
  'sessions.lastWeek': 'Last 7 days',
  'sessions.selectAll': 'Select all visible sessions',
  'sessions.selectSession': 'Select session',
  'sessions.selected': 'sessions selected',
  'sessions.bulkArchive': 'Archive selected',
  'sessions.approvalNeeded': 'Approval needed',
  'sessions.clearSelection': 'Clear selection',
  'sessions.filters': 'Session filters',
  'sessions.activeFilters': 'active filters',
  'sessions.open': 'Open session',
  'sessions.favorite': 'Add to favorites',
  'sessions.unfavorite': 'Remove from favorites',
  'sessions.more': 'Session actions',
  'sessions.rename': 'Rename',
  'sessions.archive': 'Archive',
  'sessions.restore': 'Restore',
  'sessions.delete': 'Delete',
  'sessions.emptyActive': 'No active sessions',
  'sessions.emptyFavorites': 'No favorite sessions',
  'sessions.emptyArchived': 'No archived sessions',
  'sessions.noResults': 'No matching sessions found',
  'sessions.clearSearch': 'Clear search',
  'sessions.renameTitle': 'Rename session',
  'sessions.renameDescription': 'Choose a name your team can recognize.',
  'sessions.sessionName': 'Session name',
  'sessions.cancel': 'Cancel',
  'sessions.save': 'Save',
  'sessions.deleteTitle': 'Delete session',
  'sessions.deleteDescription': 'This permanently deletes the session and its history. This action cannot be undone.',
  'sessions.deleteConfirm': 'Delete session',
  'sessions.menuLabel': 'Session actions menu',
}

const translations: Record<Locale, Record<TranslationKey, string>> = { zh, en }

type PreferencesValue = {
  theme: Theme
  locale: Locale
  setTheme: (theme: Theme) => void
  setLocale: (locale: Locale) => void
  toggleTheme: () => void
  toggleLocale: () => void
  t: (key: TranslationKey) => string
}

const PreferencesContext = createContext<PreferencesValue | null>(null)

function readPreference(key: string) {
  try {
    return window.localStorage.getItem(key)
  } catch {
    return null
  }
}

function writePreference(key: string, value: string) {
  try {
    window.localStorage.setItem(key, value)
  } catch {
    // The selected preference still applies for this browser session.
  }
}

function getInitialTheme(): Theme {
  // The live Cosmos product is light by default; only follow an explicit OS
  // dark preference or a stored choice away from that baseline.
  if (typeof window === 'undefined') return 'light'

  const stored = readPreference(PREFERENCE_STORAGE_KEYS.theme)
  if (stored === 'dark' || stored === 'light') return stored

  return window.matchMedia?.('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'
}

function getInitialLocale(): Locale {
  if (typeof window === 'undefined') return 'zh'

  const stored = readPreference(PREFERENCE_STORAGE_KEYS.locale)
  if (stored === 'zh' || stored === 'en') return stored

  return window.navigator.language.toLowerCase().startsWith('zh') ? 'zh' : 'en'
}

export function PreferencesProvider({ children }: { children: ReactNode }) {
  const [theme, setTheme] = useState<Theme>(getInitialTheme)
  const [locale, setLocale] = useState<Locale>(getInitialLocale)

  useEffect(() => {
    document.documentElement.dataset.theme = theme
    let themeColor = document.querySelector<HTMLMetaElement>('meta[name="theme-color"]')
    if (!themeColor) {
      themeColor = document.createElement('meta')
      themeColor.name = 'theme-color'
      document.head.append(themeColor)
    }
    themeColor.content = theme === 'dark' ? '#0c0d0e' : '#ffffff'
    writePreference(PREFERENCE_STORAGE_KEYS.theme, theme)
  }, [theme])

  useEffect(() => {
    document.documentElement.lang = locale === 'zh' ? 'zh-CN' : 'en'
    writePreference(PREFERENCE_STORAGE_KEYS.locale, locale)
  }, [locale])

  const toggleTheme = useCallback(() => {
    setTheme((current) => current === 'dark' ? 'light' : 'dark')
  }, [])

  const toggleLocale = useCallback(() => {
    setLocale((current) => current === 'zh' ? 'en' : 'zh')
  }, [])

  const t = useCallback((key: TranslationKey) => translations[locale][key], [locale])

  const value = useMemo<PreferencesValue>(() => ({
    theme,
    locale,
    setTheme,
    setLocale,
    toggleTheme,
    toggleLocale,
    t,
  }), [locale, t, theme, toggleLocale, toggleTheme])

  return <PreferencesContext.Provider value={value}>{children}</PreferencesContext.Provider>
}

export function usePreferences() {
  const context = useContext(PreferencesContext)
  if (!context) throw new Error('usePreferences must be used within PreferencesProvider')
  return context
}
