import {
  CONTROL_PLANE_SCHEMA_VERSION,
  type ControlPlaneState,
  type MemoryFile,
} from './types'

const seededAt = '2026-07-12T03:00:00.000Z'

function memoryFile(
  id: string,
  spaceId: string,
  path: string,
  description: string,
  content: string,
): MemoryFile {
  return {
    id,
    spaceId,
    path,
    description,
    content,
    version: 1,
    versions: [{
      id: `${id}-v1`,
      version: 1,
      content,
      createdAt: seededAt,
      createdBy: 'system-seed',
    }],
    createdAt: seededAt,
    updatedAt: seededAt,
  }
}

export function createSeededControlPlaneState(): ControlPlaneState {
  return {
    schemaVersion: CONTROL_PLANE_SCHEMA_VERSION,
    activeSpaceId: 'space-commerce',
    spaces: [
      {
        id: 'space-commerce',
        name: 'Commerce Engineering',
        slug: 'commerce',
        description: 'Payment, billing, and inventory delivery systems.',
        region: 'cn-east-1',
        createdAt: seededAt,
      },
      {
        id: 'space-platform',
        name: 'Platform Engineering',
        slug: 'platform',
        description: 'Identity and internal developer platform systems.',
        region: 'cn-east-1',
        createdAt: seededAt,
      },
    ],
    environments: [
      {
        id: 'env-commerce-default',
        spaceId: 'space-commerce',
        name: 'Commerce default',
        slug: 'commerce-default',
        image: 'cosmos-ubuntu-22.04',
        status: 'ready',
        cpu: 4,
        memoryGb: 8,
        timeoutMinutes: 45,
        networkPolicy: 'allowlist',
        allowedHosts: ['github.com', 'api.github.com', 'registry.npmjs.org'],
        provisioning: {
          phase: 'ready',
          progress: 100,
          message: 'Environment is ready',
          updatedAt: seededAt,
        },
        createdAt: seededAt,
        updatedAt: seededAt,
      },
      {
        id: 'env-commerce-browser',
        spaceId: 'space-commerce',
        name: 'Browser verification',
        slug: 'commerce-browser',
        image: 'node-22-browser',
        status: 'ready',
        cpu: 2,
        memoryGb: 4,
        timeoutMinutes: 30,
        networkPolicy: 'allowlist',
        allowedHosts: ['github.com', 'playwright.dev'],
        provisioning: {
          phase: 'ready',
          progress: 100,
          message: 'Environment is ready',
          updatedAt: seededAt,
        },
        createdAt: seededAt,
        updatedAt: seededAt,
      },
      {
        id: 'env-platform-default',
        spaceId: 'space-platform',
        name: 'Platform services',
        slug: 'platform-services',
        image: 'go-1.24-services',
        status: 'ready',
        cpu: 4,
        memoryGb: 8,
        timeoutMinutes: 45,
        networkPolicy: 'restricted',
        allowedHosts: [],
        provisioning: {
          phase: 'ready',
          progress: 100,
          message: 'Environment is ready',
          updatedAt: seededAt,
        },
        createdAt: seededAt,
        updatedAt: seededAt,
      },
    ],
    daemons: [
      {
        id: 'daemon-commerce-runner',
        spaceId: 'space-commerce',
        name: 'Commerce runner',
        description: 'Executes repository-aware Expert runs for Commerce Engineering.',
        environmentId: 'env-commerce-default',
        enabled: true,
        status: 'online',
        capabilities: ['code-search', 'shell', 'git', 'pull-request'],
        lastHeartbeatAt: seededAt,
        createdAt: seededAt,
        updatedAt: seededAt,
      },
      {
        id: 'daemon-commerce-events',
        spaceId: 'space-commerce',
        name: 'Event router',
        description: 'Matches inbound GitHub and Slack events to enabled automations.',
        environmentId: 'env-commerce-default',
        enabled: true,
        status: 'online',
        capabilities: ['webhook-routing', 'event-deduplication'],
        lastHeartbeatAt: seededAt,
        createdAt: seededAt,
        updatedAt: seededAt,
      },
      {
        id: 'daemon-platform-runner',
        spaceId: 'space-platform',
        name: 'Platform runner',
        description: 'Executes service analysis in the Platform space.',
        environmentId: 'env-platform-default',
        enabled: false,
        status: 'offline',
        capabilities: ['code-search', 'shell', 'git'],
        createdAt: seededAt,
        updatedAt: seededAt,
      },
    ],
    repositories: [
      {
        id: 'repo-payment-service',
        spaceId: 'space-commerce',
        provider: 'github',
        owner: 'commerce',
        name: 'payment-service',
        fullName: 'commerce/payment-service',
        defaultBranch: 'main',
        language: 'TypeScript',
        installationId: 'gh-install-commerce',
        indexStatus: 'ready',
        indexCoverage: 100,
        policy: 'strict',
        lastSyncedAt: seededAt,
        createdAt: seededAt,
        updatedAt: seededAt,
      },
      {
        id: 'repo-billing-web',
        spaceId: 'space-commerce',
        provider: 'github',
        owner: 'commerce',
        name: 'billing-web',
        fullName: 'commerce/billing-web',
        defaultBranch: 'main',
        language: 'TypeScript',
        installationId: 'gh-install-commerce',
        indexStatus: 'ready',
        indexCoverage: 98,
        policy: 'standard',
        lastSyncedAt: '2026-07-12T02:52:00.000Z',
        createdAt: seededAt,
        updatedAt: seededAt,
      },
      {
        id: 'repo-inventory-service',
        spaceId: 'space-commerce',
        provider: 'github',
        owner: 'commerce',
        name: 'inventory-service',
        fullName: 'commerce/inventory-service',
        defaultBranch: 'main',
        language: 'Go',
        installationId: 'gh-install-commerce',
        indexStatus: 'stale',
        indexCoverage: 96,
        policy: 'standard',
        lastSyncedAt: '2026-07-12T02:39:00.000Z',
        createdAt: seededAt,
        updatedAt: seededAt,
      },
      {
        id: 'repo-identity-service',
        spaceId: 'space-platform',
        provider: 'github',
        owner: 'platform',
        name: 'identity-service',
        fullName: 'platform/identity-service',
        defaultBranch: 'main',
        language: 'Kotlin',
        installationId: 'gh-install-platform',
        indexStatus: 'ready',
        indexCoverage: 100,
        policy: 'strict',
        lastSyncedAt: '2026-07-12T02:00:00.000Z',
        createdAt: seededAt,
        updatedAt: seededAt,
      },
    ],
    integrations: [
      {
        id: 'integration-github-commerce',
        spaceId: 'space-commerce',
        type: 'github',
        name: 'GitHub Enterprise',
        status: 'connected',
        health: 'healthy',
        scopes: ['contents:read', 'issues:write', 'pull_requests:write', 'checks:read'],
        externalAccount: 'acme-commerce',
        connectedAt: seededAt,
        lastEventAt: '2026-07-12T02:58:00.000Z',
        createdAt: seededAt,
        updatedAt: seededAt,
      },
      {
        id: 'integration-slack-commerce',
        spaceId: 'space-commerce',
        type: 'slack',
        name: 'Slack',
        status: 'connected',
        health: 'healthy',
        scopes: ['channels:history', 'chat:write', 'app_mentions:read'],
        externalAccount: 'acme-eng',
        connectedAt: seededAt,
        lastEventAt: '2026-07-12T02:55:00.000Z',
        createdAt: seededAt,
        updatedAt: seededAt,
      },
      {
        id: 'integration-jira-commerce',
        spaceId: 'space-commerce',
        type: 'jira',
        name: 'Jira Cloud',
        status: 'connected',
        health: 'healthy',
        scopes: ['read:jira-work', 'write:jira-work'],
        externalAccount: 'acme-commerce.atlassian.net',
        connectedAt: seededAt,
        createdAt: seededAt,
        updatedAt: seededAt,
      },
      {
        id: 'integration-pagerduty-commerce',
        spaceId: 'space-commerce',
        type: 'pagerduty',
        name: 'PagerDuty',
        status: 'action_required',
        health: 'degraded',
        scopes: ['incidents:read'],
        externalAccount: 'commerce-on-call',
        diagnostic: 'Webhook subscription is missing.',
        createdAt: seededAt,
        updatedAt: seededAt,
      },
    ],
    mcpServers: [
      {
        id: 'mcp-github-commerce',
        spaceId: 'space-commerce',
        name: 'GitHub MCP',
        transport: 'http',
        endpoint: 'https://mcp.internal.example/github',
        args: [],
        enabled: true,
        status: 'connected',
        toolCount: 18,
        secretIds: ['secret-github-app'],
        createdAt: seededAt,
        updatedAt: seededAt,
      },
    ],
    secrets: [
      {
        id: 'secret-github-app',
        spaceId: 'space-commerce',
        name: 'GitHub App credentials',
        provider: 'vault',
        reference: 'vault://cosmos/commerce/github-app',
        description: 'Reference to the Commerce GitHub App credentials.',
        lastFour: '4821',
        lastUsedAt: '2026-07-12T02:58:00.000Z',
        createdAt: seededAt,
        updatedAt: seededAt,
      },
      {
        id: 'secret-slack-bot',
        spaceId: 'space-commerce',
        name: 'Slack bot token',
        provider: 'vault',
        reference: 'vault://cosmos/commerce/slack-bot',
        description: 'Reference to the Slack bot token.',
        lastFour: '9137',
        lastUsedAt: '2026-07-12T02:55:00.000Z',
        createdAt: seededAt,
        updatedAt: seededAt,
      },
    ],
    webhooks: [
      {
        id: 'webhook-github-commerce',
        spaceId: 'space-commerce',
        name: 'GitHub events',
        url: 'https://cosmos.example/hooks/github/commerce',
        events: ['issues.opened', 'pull_request.ready_for_review', 'pull_request.synchronize'],
        secretId: 'secret-github-app',
        enabled: true,
        status: 'healthy',
        lastDeliveryAt: '2026-07-12T02:58:00.000Z',
        createdAt: seededAt,
        updatedAt: seededAt,
      },
      {
        id: 'webhook-slack-commerce',
        spaceId: 'space-commerce',
        name: 'Slack events',
        url: 'https://cosmos.example/hooks/slack/commerce',
        events: ['message.posted', 'app_mention'],
        secretId: 'secret-slack-bot',
        enabled: true,
        status: 'healthy',
        lastDeliveryAt: '2026-07-12T02:55:00.000Z',
        createdAt: seededAt,
        updatedAt: seededAt,
      },
    ],
    memoryFiles: [
      memoryFile(
        'memory-commerce-agents',
        'space-commerce',
        'AGENTS.md',
        'Workspace instructions shared with Commerce Experts.',
        '# Commerce Engineering\n\nKeep changes scoped, preserve API compatibility, and include verification evidence.\n',
      ),
      memoryFile(
        'memory-payment-architecture',
        'space-commerce',
        'docs/payment-architecture.md',
        'Payment service boundaries and retry policy notes.',
        '# Payment architecture\n\nPayment retries must remain idempotent and respect provider budgets.\n',
      ),
    ],
    automations: [
      {
        id: 'automation-github-issue-pr',
        spaceId: 'space-commerce',
        name: 'Payment issue to pull request',
        description: 'Starts the PR author Expert for new payment-service issues.',
        trigger: 'issues.opened',
        source: 'github',
        filter: {
          'repository.full_name': 'commerce/payment-service',
          action: 'opened',
        },
        enabled: true,
        expertId: 'expert-seed-pr-author',
        repositoryId: 'repo-payment-service',
        matchCount: 14,
        lastMatchedAt: '2026-07-12T02:58:00.000Z',
        createdAt: seededAt,
        updatedAt: seededAt,
      },
      {
        id: 'automation-slack-incident',
        spaceId: 'space-commerce',
        name: 'Payments alert investigation',
        description: 'Starts incident investigation from the payments alert channel.',
        trigger: 'message.posted',
        source: 'slack',
        filter: {
          channel: 'payments-alerts',
          mentionsCosmos: 'true',
        },
        enabled: true,
        expertId: 'expert-seed-incident-investigator',
        repositoryId: 'repo-payment-service',
        matchCount: 9,
        lastMatchedAt: '2026-07-12T02:55:00.000Z',
        createdAt: seededAt,
        updatedAt: seededAt,
      },
      {
        id: 'automation-pr-review',
        spaceId: 'space-commerce',
        name: 'Deep review for ready pull requests',
        description: 'Runs a deep review when a Commerce pull request is ready.',
        trigger: 'pull_request.ready_for_review',
        source: 'github',
        filter: {
          'repository.owner': 'commerce',
        },
        enabled: true,
        expertId: 'expert-seed-deep-code-reviewer',
        matchCount: 31,
        lastMatchedAt: '2026-07-12T02:40:00.000Z',
        createdAt: seededAt,
        updatedAt: seededAt,
      },
    ],
    inboundEvents: [
      {
        id: 'event-seed-github-772',
        spaceId: 'space-commerce',
        source: 'github',
        trigger: 'issues.opened',
        externalId: 'github:issue:772',
        payload: {
          action: 'opened',
          title: 'Add concurrency coverage to inventory reservation',
          repository: { full_name: 'commerce/inventory-service', owner: 'commerce' },
        },
        status: 'unmatched',
        receivedAt: '2026-07-12T02:30:00.000Z',
        createdAt: '2026-07-12T02:30:00.000Z',
        updatedAt: '2026-07-12T02:30:00.000Z',
      },
      {
        id: 'event-seed-slack-payment-alert',
        spaceId: 'space-commerce',
        source: 'slack',
        trigger: 'message.posted',
        externalId: 'slack:event:payments-alerts:482',
        payload: {
          channel: 'payments-alerts',
          mentionsCosmos: true,
          text: 'Investigate intermittent payment callback timeouts.',
        },
        status: 'matched',
        matchedAutomationId: 'automation-slack-incident',
        matchedSessionId: 'session-draft-seed-payment-alert',
        receivedAt: '2026-07-12T02:55:00.000Z',
        createdAt: '2026-07-12T02:55:00.000Z',
        updatedAt: '2026-07-12T02:55:00.000Z',
      },
    ],
    sessionDrafts: [
      {
        id: 'session-draft-seed-payment-alert',
        spaceId: 'space-commerce',
        title: 'Investigate intermittent payment callback timeouts.',
        status: 'draft',
        sourceEventId: 'event-seed-slack-payment-alert',
        automationId: 'automation-slack-incident',
        expertId: 'expert-seed-incident-investigator',
        repositoryId: 'repo-payment-service',
        summary: 'Created from Slack message.posted via Payments alert investigation.',
        createdAt: '2026-07-12T02:55:00.000Z',
        updatedAt: '2026-07-12T02:55:00.000Z',
      },
    ],
    auditEvents: [
      {
        id: 'audit-seed-slack-match',
        spaceId: 'space-commerce',
        actor: 'event-router',
        action: 'inbound_event.matched',
        targetType: 'inbound_event',
        targetId: 'event-seed-slack-payment-alert',
        channel: 'automation',
        result: 'success',
        metadata: {
          automationId: 'automation-slack-incident',
          sessionId: 'session-draft-seed-payment-alert',
        },
        createdAt: '2026-07-12T02:55:00.000Z',
        updatedAt: '2026-07-12T02:55:00.000Z',
      },
      {
        id: 'audit-seed-expert-publish',
        spaceId: 'space-commerce',
        actor: 'system-seed',
        action: 'expert.published',
        targetType: 'expert',
        targetId: 'expert-seed-pr-author',
        channel: 'system',
        result: 'success',
        metadata: { version: 1 },
        createdAt: seededAt,
        updatedAt: seededAt,
      },
    ],
  }
}

export function createEmptyControlPlaneState(
  spaceId: string,
  spaces: ReadonlyArray<{ id: string; name: string }> = [{ id: spaceId, name: 'Authorized Space' }],
): ControlPlaneState {
  const authorizedSpaces = spaces.some((space) => space.id === spaceId)
    ? spaces
    : [{ id: spaceId, name: 'Authorized Space' }, ...spaces]
  return {
    schemaVersion: CONTROL_PLANE_SCHEMA_VERSION,
    activeSpaceId: spaceId,
    spaces: authorizedSpaces.map((space) => ({
      id: space.id,
      name: space.name,
      slug: space.id,
      description: '',
      region: '',
      createdAt: new Date(0).toISOString(),
    })),
    environments: [],
    daemons: [],
    repositories: [],
    integrations: [],
    mcpServers: [],
    secrets: [],
    webhooks: [],
    memoryFiles: [],
    automations: [],
    inboundEvents: [],
    sessionDrafts: [],
    auditEvents: [],
  }
}
